services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
